volumes:
  db: {}

services:
  bot:
    build: .
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_TOKEN: ${YOUR_DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - db:/data
